# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Execute Build

on:
  push:
    branches:
      - master
      - feature/**
      - hotfix/**
      - bugfix/**
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 21
    - name: Build with Maven
      run: mvn -B install --file gw2-tools-backend/pom.xml
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: cd gw2-tools-ui && npm ci
